language: python
sudo: required
dist: xenial
python: "3.6"
install:
- pip install -r requirements.test.txt
before_script:
- sudo useradd bigacmeuser
script:
- sudo $(which pytest) --lb $LB --pass $PASS --system-user bigacmeuser --cov=bigacme
after_success:
- codecov
